# Generated by Django 5.2 on 2025-04-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('internalReference', models.CharField(blank=True, max_length=100, null=True)),
                ('shellId', models.IntegerField()),
                ('inventoryStatus', models.CharField(choices=[('INSTOCK', 'In Stock'), ('LOWSTOCK', 'Low Stock'), ('OUTOFSTOCK', 'Out of Stock')], max_length=20)),
                ('rating', models.FloatField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
